# -*- coding: utf-8 -*-
"""aula 03 LPC1 PD.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fZFKlZoY5BsTIRRWjwARqfgRkOv6KJBf
"""

# ETE PORTO DIGITAL
# DISCIPLINA LPC1
# PROFRESSOR: CLOVES
# ESTUDANTE: MATEUS ALVES DE ALMEIDA

print ('Olá, ETE PORTO DIGITAL!')